linters:
  enable:
    - gofmt
    - bodyclose
    - exhaustive
    - dupl
    - errorlint
    - prealloc
    - importas
    - errorlint
    - errname
    - revive
    - gocritic
    - staticcheck
    - gosimple
    - govet
    - ineffassign
    - typecheck
    - unused
    - misspell
    - goimports
    - tenv
    - gochecknoinits
    - usestdlibvars
    - thelper
    - nolintlint
    - noctx
    - wrapcheck
    - gocognit
    - exportloopref

linters-settings:
  
  exhaustive:
    default-signifies-exhaustive: true

  staticcheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.20"
    # https://staticcheck.io/docs/options#checks
    checks: [ "all" ]

  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: atomic
      # - name: line-length-limit
      #   severity: warning
      #   arguments: [120]
      - name: unhandled-error
        arguments:
        - fmt.Printf
        - fmt.Println
        - fmt.Print
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      # - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: defer
      - name: useless-break
      - name: unexported-naming
      # - name: cognitive-complexity
      #   arguments: [35]
      - name: use-any
      - name: deep-exit
      # - name: add-constant
      - name: unnecessary-stmt
      - name: modifies-value-receiver
      # - name: constant-logical-expr
      - name: call-to-gc
      - name: import-shadowing
      - name: imports-blacklist
        arguments:
        - sync

  wrapcheck:
    ignoreSigs:
      # defaults
      - ".Errorf("
      - ".Err("
      - "errors.New("
      - "errors.Unwrap("
      - "errors.Join("
      - ".Close()" # another linter handles close err
      # expected to work
      - .ExecuteContext( # cobra command
      - (*golang.org/x/sync/errgroup.Group).Wait()
    ignoreSigRegexps:
      # ignore printing (to stdout)
      - "fmt\\..?(P|p)rint.*\\(" 
    ignorePackageGlobs:
      - encoding/*
      - fmt

  gocognit:
    min-complexity: 25

issues:
  # uncomment to enable more linting
  # exclude-use-default: false

  include:
  # - EXC0001
  - EXC0002
  - EXC0005
  - EXC0009
  - EXC0011
  - EXC0012
  - EXC0013
  - EXC0014
  - EXC0015
