name: Testing Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        # check-latest: true
    - name: Run tests
      run: go test -race ./... # -json > test.json

    # - name: Annotate tests
    #   if: always()
    #   uses: guyarb/golang-test-annotations@v0.6.0
    #   with:
    #     test-results: test.json


  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
